apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"mysql-insi-m2","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mysql"}},"serviceName":"mysql-service","template":{"metadata":{"labels":{"app":"mysql"}},"spec":{"containers":[{"args":["--innodb-buffer-pool-size=128M","--max-connections=50","--performance-schema=OFF"],"env":[{"name":"MYSQL_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"mysql-root-password","name":"mysql-secrets"}}},{"name":"MYSQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"mysql-insi-password","name":"mysql-secrets"}}},{"name":"MYSQL_DATABASE","valueFrom":{"configMapKeyRef":{"key":"MYSQL_DATABASE","name":"mysql-config"}}},{"name":"MYSQL_USER","valueFrom":{"configMapKeyRef":{"key":"MYSQL_USER","name":"mysql-config"}}}],"image":"mysql:8.0","livenessProbe":{"exec":{"command":["sh","-c","mysqladmin ping -h localhost -u $MYSQL_USER -p$MYSQL_PASSWORD"]},"initialDelaySeconds":60,"periodSeconds":20,"timeoutSeconds":5},"name":"mysql","ports":[{"containerPort":3306}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/var/lib/mysql","name":"mysql-data"}]}],"volumes":[{"name":"mysql-data","persistentVolumeClaim":{"claimName":"mysql-pvc-insi"}}]}}}}
  creationTimestamp: "2026-07-01T11:57:11Z"
  generation: 10
  name: mysql-insi-m2
  namespace: default
  resourceVersion: "2931662"
  uid: c0c125d9-954a-4aeb-a996-e6c77dcc0c81
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-service
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-07-01T16:51:23+03:00"
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - args:
        - --innodb-buffer-pool-size=128M
        - --max-connections=50
        - --performance-schema=OFF
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: mysql-secrets
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-insi-password
              name: mysql-secrets
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: mysql-config
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: mysql-config
        image: mysql:8.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -h localhost -u $MYSQL_USER -p$MYSQL_PASSWORD
          failureThreshold: 5
          initialDelaySeconds: 120
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: workernode2
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc-insi
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: mysql-insi-m2-6bb6fcccd9
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updateRevision: mysql-insi-m2-6bb6fcccd9
  updatedReplicas: 1
