apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-insi
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-insi-m2
  resources:
    requests:
      storage: 5Gi
